### ISSUE TITLE
start-transcribe-mic.bat won't working

### ISSUE THREAD

**Issue by ahmedshahzadaaa** [Sharrnah/whispering#13]
When running start-transcribe-mic.bat it is giving syntax error as shown below.
```(venv) H:\>start-transcribe-mic.bat

(venv) H:\>python audioWhisper.py --model medium --task transcribe --osc_ip 127.0.0.1 --websocket_ip 127.0.0.1 --phrase_time_limit 8 --condition_on_previous_text --open_browser

H:\venv\lib\site-packages\whisper\timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Traceback (most recent call last):
  File "audioWhisper.py", line 35, in <module>
    import audioprocessor
  File "H:\audioprocessor.py", line 8, in <module>
    from Models.TextTranslation import texttranslate
  File "H:\Models\TextTranslation\texttranslate.py", line 32
    match get_current_translator():
          ^
SyntaxError: invalid syntax

{"type": "error", "message": "invalid syntax (texttranslate.py, line 32)", "traceback": ["  File \"audioWhisper.py\", line 35, in <module>\n    import audioprocessor\n", "  File \"H:\\audioprocessor.py\", line 8, in <module>\n    from Models.TextTranslation import texttranslate\n"]}```

**Comment by ahmedshahzadaaa** [comment]
This issue is because of python<3.10.
For running this repo, You need to have python>=3.10

**Comment by Sharrnah** [comment]
Or run the standalone distribution you can find in the releases.

Or even simpler, use the UI which also downloads the standalone release but provides easier configuration: https://github.com/Sharrnah/whispering-ui
