### ISSUE TITLE
Not working with loopback devices

### ISSUE THREAD

**Issue by Infinitay** [Sharrnah/whispering#3]
```
-------------------------------------------------------------------
                           Input Devices
 In form of: DEVICE_NAME [Sample Rate=?] [Loopback?] (Index=INDEX)
-------------------------------------------------------------------
Microsoft Sound Mapper - Input [Sample Rate=44100] (Index=0)
Primary Sound Capture Driver [Sample Rate=44100] (Index=7)
Realtek Digital Output (Realtek(R) Audio) [Loopback] [Sample Rate=48000] (Index=20)
Headphones (USB-C to 3.5mm Headphone Jack Adapter) [Loopback] [Sample Rate=48000] (Index=22)
```
The first two input devices worked just fine, but the last two are having errors when passing in their index as the audio device to listen to. I believe this is because they are listed as loopback devices because it's the only difference I see.

### Error for device[20]
```
###################################
# Whispering Tiger is starting... #
###################################
Websocket: Server started.
Traceback (most recent call last):
  File "audioWhisper.py", line 154, in <module>
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "audioWhisper.py", line 126, in main
  File "speech_recognition\__init__.py", line 138, in __enter__
  File "pyaudio.py", line 754, in open
  File "pyaudio.py", line 445, in __init__
OSError: [Errno -9998] Invalid number of channels
[27916] Failed to execute script 'audioWhisper' due to unhandled exception!
```

### Error for device[22]
```
###################################
# Whispering Tiger is starting... #
###################################
Websocket: Server started.
Traceback (most recent call last):
  File "audioWhisper.py", line 154, in <module>
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "audioWhisper.py", line 126, in main
  File "speech_recognition\__init__.py", line 138, in __enter__
  File "pyaudio.py", line 754, in open
  File "pyaudio.py", line 445, in __init__
OSError: [Errno -9999] Unanticipated host error
[30984] Failed to execute script 'audioWhisper' due to unhandled exception!
```

I read the FAQ and saw the comments regarding `OSError: [Errno -9999] Unanticipated host error` but even when I tried device @ index 20 I had an issue albeit a new one. Are loopback devices not supported?

**Comment by Sharrnah** [comment]
Yes. sorry. I haven't got loopback devices working myself yet.

For now i recommend trying to use stereomix or something like voicemeeter.

Stereomix description (for windows 7, but should not have changed much in windows 10): https://www.howtogeek.com/howto/39532/how-to-enable-stereo-mix-in-windows-7-to-record-audio/

Voicemeeter: https://vb-audio.com/Voicemeeter/

I had very good results using Voicemeeter myself

and with VBAN https://vb-audio.com/Voicemeeter/vban.htm
the A.I. processing can even be "outsourced" to a second PC.

**Comment by Infinitay** [comment]
To be honest I have no idea why my audio output is even marked as a loopback device. I'll go ahead and try one of the suggestions you linked. Thank you.
